config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticate :user do
    resources :cargas
    resources :motoristas
    resources :paradas
    resources :caminhaos
    resources :enderecos
    resources :rota

    get '/search/rota', to: "rota#search", as: :rota_search
    post '/search/rota', to: "rota#search_rota"

    get '/search/motorista', to: "motoristas#search", as: :motorista_search
    post '/search/motorista', to: "motoristas#search_rotas"
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    root "home#index"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/views/home/index.html.erb
<div class="mx-auto w-1/2 p-5 flex flex-col items-center">
  <h3 class="text-zinc-800 font-bold text-2xl">Escolha uma opção para prosseguir:</h3>
  <div class="w-full grid grid-cols-3 gap-7 mt-10">
    <div class="p-5 bg-white rounded shadow-lg flex flex-col items-center gap-2">
      <i class="fa-solid fa-truck-front text-blue-500"></i>
      <p>Caminhões</p>
      <%= link_to "Caminhões", caminhaos_path, class:"text-sm bg-blue-500 text-white rounded py-1 px-2 cursor-pointer transition duration-300 hover:bg-blue-600" %>
    </div>
    <div class="p-5 bg-white rounded shadow-lg flex flex-col items-center gap-2">
      <i class="fa-solid fa-id-card text-blue-500"></i>
      <p>Motoristas</p>
      <%= link_to "Motoristas", motoristas_path, class:"text-sm bg-blue-500 text-white rounded py-1 px-2 cursor-pointer transition duration-300 hover:bg-blue-600" %><br />
    </div>
    <div class="p-5 bg-white rounded shadow-lg flex flex-col items-center gap-2">
      <i class="fa-solid fa-boxes-stacked text-blue-500"></i>
      <p>Cargas</p>
      <%= link_to "Cargas", cargas_path, class:"text-sm bg-blue-500 text-white rounded py-1 px-2 cursor-pointer transition duration-300 hover:bg-blue-600" %><br />
    </div>
    <div class="p-5 bg-white rounded shadow-lg flex flex-col items-center gap-2">
      <i class="fa-solid fa-store text-blue-500"></i>
      <p>Endereços</p>
      <%= link_to "Endereços", enderecos_path, class:"text-sm bg-blue-500 text-white rounded py-1 px-2 cursor-pointer transition duration-300 hover:bg-blue-600" %><br />
    </div>
    <div class="p-5 bg-white rounded shadow-lg flex flex-col items-center gap-2">
      <i class="fa-solid fa-map-location text-blue-500"></i>
      <p>Paradas</p>
      <%= link_to "Paradas", paradas_path, class:"text-sm bg-blue-500 text-white rounded py-1 px-2 cursor-pointer transition duration-300 hover:bg-blue-600" %><br />
    </div>
    <div class="p-5 bg-white rounded shadow-lg flex flex-col items-center gap-2">
      <i class="fa-solid fa-road text-blue-500"></i>
      <p>Rotas</p>
      <%= link_to "Rotas", rota_path, class:"text-sm bg-blue-500 text-white rounded py-1 px-2 cursor-pointer transition duration-300 hover:bg-blue-600" %><br />
    </div>
  </div>
</div>