config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticate :user do
    resources :cargas
    resources :motoristas
    resources :paradas
    resources :caminhaos
    resources :enderecos
    resources :rota

    get '/search/rota', to: "rota#search", as: :rota_search
    post '/search/rota', to: "rota#search_rota"

    get '/search/motorista', to: "motoristas#search", as: :motorista_search
    post '/search/motorista', to: "motoristas#search_rotas"
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    root "home#index"
  end
end

app/models/carga.rb
class Carga < ApplicationRecord
  has_one :rotum

  validates :descricao, presence: true
  validates :peso, presence: true, numericality: { greater_than: 0 }
  validates :volume, presence: true, numericality: { greater_than: 0 }
  validates :valor, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :numero_rastreamento, presence: true, uniqueness: true
  validates :rota_id, presence: true
end

app/controllers/cargas_controller.rb
class CargasController < ApplicationController
  before_action :set_carga, only: %i[ show edit update destroy ]

  # GET /cargas or /cargas.json
  def index
    @cargas = Carga.all
  end

  # GET /cargas/1 or /cargas/1.json
  def show
  end

  # GET /cargas/new
  def new
    @carga_atual = Carga.new
  end

  # GET /cargas/1/edit
  def edit
  end

  # POST /cargas or /cargas.json
  def create
    @carga_atual = Carga.new(carga_params)

    respond_to do |format|
      if @carga_atual.save
        carga_success(format, :created, "created")
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @carga_atual.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cargas/1 or /cargas/1.json
  def update
    respond_to do |format|
      if @carga_atual.update(carga_params)
        carga_success(format, :ok, "updated")
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @carga_atual.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cargas/1 or /cargas/1.json
  def destroy
    @carga_atual.destroy

    respond_to do |format|
      format.html { redirect_to cargas_url, notice: "Carga was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def carga_success(format, status, method)
    format.html { redirect_to carga_url(@carga_atual), notice: "Carga was successfully #{method}." }
    format.json { render :show, status: status, location: @carga_atual }
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_carga
    @carga_atual = Carga.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def carga_params
    params.require(:carga).permit(:descricao, :peso, :volume, :valor, :numero_rastreamento, :rota_id)
  end
end

app/helpers/cargas_helper.rb
module CargasHelper
end

app/views/cargas/_carga.html.erb
<div id="<%= dom_id carga %>">
  <p>
    <strong>Descricao:</strong>
    <%= carga.descricao %>
  </p>

  <p>
    <strong>Peso:</strong>
    <%= carga.peso %>
  </p>

  <p>
    <strong>Volume:</strong>
    <%= carga.volume %>
  </p>

  <p>
    <strong>Valor:</strong>
    <%= carga.valor %>
  </p>

  <p>
    <strong>Numero rastreamento:</strong>
    <%= carga.numero_rastreamento %>
  </p>

</div>

app/views/cargas/_form.html.erb
<%= form_with(model: carga) do |form| %>
  <% if carga.errors.any? %>
    <div style="color: red" class="mb-3">
      <h2><%= pluralize(carga.errors.count, "error") %> prohibited this carga from being saved:</h2>

      <ul>
        <% @carga_atual.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="p-5 bg-white rounded-lg shadow-lg grid grid-cols-2 gap-y-4 justify-center">
    <div>
      <%= form.label :descricao, style: "display: block" %>
      <%= form.text_field :descricao %>
    </div>

    <div>
      <%= form.label :peso, style: "display: block" %>
      <%= form.text_field :peso %>
    </div>

    <div>
      <%= form.label :volume, style: "display: block" %>
      <%= form.text_field :volume %>
    </div>

    <div>
      <%= form.label :valor, style: "display: block" %>
      <%= form.text_field :valor %>
    </div>

    <div>
      <%= form.label :numero_rastreamento, style: "display: block" %>
      <%= form.text_field :numero_rastreamento %>
    </div>

    <div>
      <%= form.label :rota_id, style: "display: block" %>
      <%= form.collection_select :rota_id, Rotum.all, :id, :observacoes, { prompt: 'Selecione uma Rota' }, class: 'form-control' %>
    </div>
  </div>

  <div class="mt-3 h-full flex justify-end">
    <%= form.submit :class=>"bg-blue-500 text-white rounded py-2 px-3 cursor-pointer transition duration-300 hover:bg-blue-600"%>
  </div>
<% end %>

app/views/cargas/edit.html.erb
<div class="p-5">
  <div class="mb-3">
    <span>
      <i class="fa-solid fa-chevron-left"></i>
      <%= link_to "Back to carga", @carga_atual %>
    </span>
    <h1 class="text-zinc-800 font-bold text-2xl">Editing carga</h1>
  </div>

  <%= render "form", carga: @carga_atual %>

  <br>
</div>

app/views/cargas/index.html.erb
<div class="p-5">
  <div>
    <span>
      <i class="fa-solid fa-chevron-left"></i>
      <%= link_to "Back to home", root_path %>
    </span>
    <div class="flex items-center justify-between">

      <h1 class="text-zinc-800 font-bold text-2xl">Cargas</h1>
      <%= link_to "New carga", new_carga_path, class:"text-sm bg-blue-500 text-white rounded py-1 px-2 cursor-pointer transition duration-300 hover:bg-blue-600" %>
    </div>
  </div>

    <div id="cargas" class="mt-3 flex flex-col gap-5">
      <% @cargas.each do |carga| %>
        <div class="p-5 bg-white rounded-lg shadow-lg flex justify-between">
          <%= render carga %>
          <p>
            <%= link_to "Show this carga", carga,class:"py-2 px-3 rounded-lg cursor-pointer transition duration-300 hover:bg-slate-800 hover:text-white" %>
          </p>
        </div>
    <% end %>
    </div>
</div>

app/views/cargas/new.html.erb
<div class="p-5">
  <div class="mb-3">
    <span>
      <i class="fa-solid fa-chevron-left"></i>
      <%= link_to "Back to cargas", cargas_path %>
    </span>
    <h1 class="text-zinc-800 font-bold text-2xl">New carga</h1>
  </div>

  <%= render "form", carga: @carga_atual %>

  <br>
</div>

app/views/cargas/show.html.erb
<div class="p-5">
  <div class="mb-3">
    <span>
      <i class="fa-solid fa-chevron-left"></i>
      <%= link_to "Back to cargas", cargas_path %>
    </span>
    <h1 class="text-zinc-800 font-bold text-2xl">Visualizar Carga</h1>
  </div>

  <div class="p-5 bg-white rounded-lg shadow-lg flex justify-between">
    <%= render @carga_atual %>

    <div class="flex flex-col gap-3">
      <%= link_to "Edit this carga", edit_carga_path(@carga_atual),  class:"bg-slate-500 text-white rounded py-2 px-3 cursor-pointer transition duration-300 hover:bg-slate-600" %>
      <%= button_to "Destroy this carga", @carga_atual, method: :delete, class:"bg-red-500 text-white rounded py-2 px-3 cursor-pointer transition duration-300 hover:bg-red-600" %>
    </div>
  </div>
</div>