config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticate :user do
    resources :cargas
    resources :motoristas
    resources :paradas
    resources :caminhaos
    resources :enderecos
    resources :rota

    get '/search/rota', to: "rota#search", as: :rota_search
    post '/search/rota', to: "rota#search_rota"

    get '/search/motorista', to: "motoristas#search", as: :motorista_search
    post '/search/motorista', to: "motoristas#search_rotas"
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    root "home#index"
  end
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  # belongs_to :rotum
  #has_many :paradas, dependent: :destroy
  has_many :rotum, dependent: :nullify
  validates :cidade, presence: true, length: { minimum: 5, maximum: 50 }
  validates :cep, presence: true, format: { with: /\A\d{8}\z/, message: "deve conter 8 dígitos numéricos" }
end

app/controllers/enderecos_controller.rb
class EnderecosController < ApplicationController
  before_action :set_endereco, only: %i[ show edit update destroy ]

  # GET /enderecos or /enderecos.json
  def index
    @enderecos = Endereco.all
  end

  # GET /enderecos/1 or /enderecos/1.json
  def show
  end

  # GET /enderecos/new
  def new
    @endereco_atual = Endereco.new
  end

  # GET /enderecos/1/edit
  def edit
  end

  # POST /enderecos or /enderecos.json
  def create
    @endereco_atual = Endereco.new(endereco_params)

    respond_to do |format|
      if @endereco_atual.save
        endereco_success(format, :created, "created")
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @endereco_atual.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enderecos/1 or /enderecos/1.json
  def update
    respond_to do |format|
      if @endereco_atual.update(endereco_params)
        endereco_success(format, :ok, "updated")
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @endereco_atual.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enderecos/1 or /enderecos/1.json
  def destroy
    @endereco_atual.destroy

    respond_to do |format|
      format.html { redirect_to enderecos_url, notice: "Endereco was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def endereco_success(format, status, method)
    format.html { redirect_to endereco_url(@endereco_atual), notice: "Endereco was successfully #{method}." }
    format.json { render :show, status: status, location: @endereco_atual }
  end

  # Use callbacks to share common setup or constraints between actions.
    def set_endereco
      @endereco_atual = Endereco.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def endereco_params
      params.require(:endereco).permit(:cidade, :cep)
    end
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/views/enderecos/_endereco.html.erb
<div id="<%= dom_id endereco %>">
  <p>
    <strong>Cidade:</strong>
    <%= endereco.cidade %>
  </p>

  <p>
    <strong>Cep:</strong>
    <%= endereco.cep %>
  </p>

</div>

app/views/enderecos/_form.html.erb
<%= form_with(model: endereco) do |form| %>
  <% if endereco.errors.any? %>
    <div style="color: red" class="mb-3">
      <h2><%= pluralize(endereco.errors.count, "error") %> prohibited this endereco from being saved:</h2>

      <ul>
        <% endereco.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="p-5 bg-white rounded-lg shadow-lg grid grid-cols-2 gap-y-4 justify-center">
    <div>
      <%= form.label :cidade, style: "display: block" %>
      <%= form.text_field :cidade %>
    </div>

    <div>
      <%= form.label :cep, style: "display: block" %>
      <%= form.number_field :cep %>
    </div>
  </div>

  <div class="mt-3 h-full flex justify-end">
    <%= form.submit :class=>"bg-blue-500 text-white rounded py-2 px-3 cursor-pointer transition duration-300 hover:bg-blue-600"%>
  </div>
<% end %>

app/views/enderecos/edit.html.erb
<div class="p-5">
  <div class="mb-3">
    <span>
      <i class="fa-solid fa-chevron-left"></i>
      <%= link_to "Back to endereco", @caminhao_atual %>
    </span>
    <h1 class="text-zinc-800 font-bold text-2xl">Editing endereco</h1>
  </div>

  <%= render "form", endereco: @endereco_atual %>

  <br>
</div>

app/views/enderecos/index.html.erb
<div class="p-5">
  <div>
    <span>
      <i class="fa-solid fa-chevron-left"></i>
      <%= link_to "Back to home", root_path %>
    </span>
    <div class="flex items-center justify-between">

      <h1 class="text-zinc-800 font-bold text-2xl">Enderecos</h1>
      <%= link_to "New endereco", new_endereco_path, class:"text-sm bg-blue-500 text-white rounded py-1 px-2 cursor-pointer transition duration-300 hover:bg-blue-600" %>
    </div>
  </div>

  <div id="enderecos" class="mt-3 flex flex-col gap-5">
     <% @enderecos.each do |endereco| %>
      <div class="p-5 bg-white rounded-lg shadow-lg flex justify-between">
       <%= render endereco %>
       <p>
         <%= link_to "Show this endereco", endereco, class:"py-2 px-3 rounded-lg cursor-pointer transition duration-300 hover:bg-slate-800 hover:text-white" %>
       </p>
      </div>
     <% end %>
  </div>
</div>

app/views/enderecos/new.html.erb
<div class="p-5">
  <div class="mb-3">
    <span>
      <i class="fa-solid fa-chevron-left"></i>
      <%= link_to "Back to enderecos", enderecos_path %>
    </span>
    <h1 class="text-zinc-800 font-bold text-2xl">New endereco</h1>
  </div>

  <%= render "form", endereco: @endereco_atual %>

  <br>
</div>

app/views/enderecos/show.html.erb
<div class="p-5">
  <div class="mb-3">
    <span>
      <i class="fa-solid fa-chevron-left"></i>
      <%= link_to "Back to enderecos", enderecos_path %>
    </span>
    <h1 class="text-zinc-800 font-bold text-2xl">Visualizar Endereço</h1>
  </div>

  <div class="p-5 bg-white rounded-lg shadow-lg flex justify-between">
    <%= render @endereco_atual %>

    <div class="flex flex-col gap-3">
      <%= link_to "Edit this endereco", edit_endereco_path(@endereco_atual), class:"bg-slate-500 text-white rounded py-2 px-3 cursor-pointer transition duration-300 hover:bg-slate-600" %>
      <%= button_to "Destroy this endereco", @endereco_atual, method: :delete, class:"bg-red-500 text-white rounded py-2 px-3 cursor-pointer transition duration-300 hover:bg-red-600" %>
    </div>
  </div>
</div>