config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticate :user do
    resources :cargas
    resources :motoristas
    resources :paradas
    resources :caminhaos
    resources :enderecos
    resources :rota

    get '/search/rota', to: "rota#search", as: :rota_search
    post '/search/rota', to: "rota#search_rota"

    get '/search/motorista', to: "motoristas#search", as: :motorista_search
    post '/search/motorista', to: "motoristas#search_rotas"
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    root "home#index"
  end
end

app/models/motorista.rb
class Motorista < ApplicationRecord
  belongs_to :caminhao

  validates :nome, presence: true, length: { minimum: 5, maximum: 50 }
  validates :cpf, presence: true, length: { is: 11}, numericality: true
  validates :cnh, presence: true, length: { is: 11}, numericality: true
  validates :telefone, presence: true, length: { is: 11}, numericality: true
  validate :valida_data_nascimento
  validates :caminhao_id, presence: true

  def valida_data_nascimento
    if data_nascimento.blank? || data_nascimento > (Date.today - 18.years)
      errors.add(:data_nascimento, ", Motorista deve ser maior de idade")
    end
  end
end

app/controllers/motoristas_controller.rb
class MotoristasController < ApplicationController
  before_action :set_motorista, only: %i[ show edit update destroy ]

  # GET /motoristas or /motoristas.json
  def index
    @motoristas = Motorista.all
  end

  # GET /motoristas/1 or /motoristas/1.json
  def show
  end

  # GET /motoristas/new
  def new
    @motorista = Motorista.new
  end

  # GET /motoristas/1/edit
  def edit
  end

  # POST /motoristas or /motoristas.json
  def create
    @motorista = Motorista.new(motorista_params)

    respond_to do |format|
      if @motorista.save
        motorista_success(format, :created, "created")
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @motorista.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /motoristas/1 or /motoristas/1.json
  def update
    respond_to do |format|
      if @motorista.update(motorista_params)
        motorista_success(format, :ok, "updated")
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @motorista.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /motoristas/1 or /motoristas/1.json
  def destroy
    @motorista.destroy

    respond_to do |format|
      format.html { redirect_to motoristas_url, notice: "Motorista was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search_rotas
    if params[:cpf].blank?
      @error = "Cpf/Nome nao pode esta vazio"
    else
      motorista_cpf = Motorista.where(cpf: params[:cpf])
      motorista_nome = Motorista.where(nome: params[:cpf])

      if motorista_cpf.empty? and motorista_nome.empty?
        @error = "Sem motoristas com esse nome/cpf"
      end
    end

    if !@error.to_s.empty?
      respond_to do |format|
        format.html { render :search}
      end
    else

      if motorista_cpf.empty?
        puts "pesquisou por nome"
        @motorista = Motorista.find_by(nome: params[:cpf])
      else
        puts "pesquisou por cpf"
        @motorista = Motorista.find_by(cpf: params[:cpf])
      end

      @rotas = Rotum.joins(caminhao: :motorista).where(motoristas: { nome: @motorista.nome })
      print(@rotas.inspect)
      respond_to do |format|
        format.html { render :show_result}
      end
    end
  end

  private

  def motorista_success(format, status, method)
    format.html { redirect_to motorista_url(@motorista), notice: "Motorista was successfully #{method}." }
    format.json { render :show, status: status, location: @motorista }
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_motorista
    @motorista = Motorista.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def motorista_params
    params.require(:motorista).permit(:nome, :cpf, :cnh, :telefone, :data_nascimento, :caminhao_id)
  end
end

app/helpers/motoristas_helper.rb
module MotoristasHelper
end

app/views/motoristas/_form.html.erb
<%= form_with(model: motorista) do |form| %>
  <% if motorista.errors.any? %>
    <div style="color: red" class="mb-3">
      <h2><%= pluralize(motorista.errors.count, "error") %> prohibited this motorista from being saved:</h2>

      <ul>
        <% motorista.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="p-5 bg-white rounded-lg shadow-lg grid grid-cols-2 gap-y-4 justify-center">
    <div>
      <%= form.label :nome, style: "display: block" %>
      <%= form.text_field :nome %>
    </div>

    <div>
      <%= form.label :cpf, style: "display: block" %>
      <%= form.number_field :cpf %>
    </div>

    <div>
      <%= form.label :cnh, style: "display: block" %>
      <%= form.number_field :cnh %>
    </div>

    <div>
      <%= form.label :telefone, style: "display: block" %>
      <%= form.number_field :telefone %>
    </div>

    <div>
      <%= form.label :data_nascimento, style: "display: block" %>
      <%= form.date_field :data_nascimento %>
    </div>

    <div>
      <%= form.label :caminhao_id, style: "display: block" %>
      <%= form.collection_select :caminhao_id, Caminhao.all, :id, :placa, { prompt: 'Selecione um Caminhão' }, class: 'form-control' %>
    </div>
  </div>

  <div class="mt-3 h-full flex justify-end">
    <%= form.submit :class=>"bg-blue-500 text-white rounded py-2 px-3 cursor-pointer transition duration-300 hover:bg-blue-600"%>
  </div>
<% end %>

app/views/motoristas/_motorista.html.erb
<div id="<%= dom_id motorista %>">
  <p>
    <strong>Nome:</strong>
    <%= motorista.nome %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= motorista.cpf %>
  </p>

  <p>
    <strong>Cnh:</strong>
    <%= motorista.cnh %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= motorista.telefone %>
  </p>

  <p>
    <strong>Data nascimento:</strong>
    <%= motorista.data_nascimento %>
  </p>

  <p>
    <strong>Caminhao:</strong>
    <%= motorista.caminhao.placa if motorista.caminhao.present? %>
  </p>

</div>

app/views/motoristas/edit.html.erb
<div class="p-5">
  <div class="mb-3">
    <span>
      <i class="fa-solid fa-chevron-left"></i>
      <%= link_to "Back to motorista", @motorista %>
    </span>
    <h1 class="text-zinc-800 font-bold text-2xl">Editing motorista</h1>
  </div>

  <%= render "form", motorista: @motorista %>

  <br>
</div>

app/views/motoristas/index.html.erb
<div class="p-5">
  <div>
    <span>
      <i class="fa-solid fa-chevron-left"></i>
      <%= link_to "Back to home", root_path %>
    </span>
    <div class="flex items-center justify-between">
      <h1 class="text-zinc-800 font-bold text-2xl">Motoristas</h1>
      <div class="flex gap-3">
        <%= link_to "New motorista", new_motorista_path,class:"text-sm bg-blue-500 text-white rounded py-1 px-2 cursor-pointer transition duration-300 hover:bg-blue-600"%>
        <%= link_to "Find motorista", search_motorista_path ,class:"text-sm bg-blue-500 text-white rounded py-1 px-2 cursor-pointer transition duration-300 hover:bg-blue-600"%>
      </div>
    </div>
  </div>

  <div id="motoristas" class="mt-3 flex flex-col gap-5">
    <% @motoristas.each do |motorista| %>
      <div class="p-5 bg-white rounded-lg shadow-lg flex justify-between">
        <%= render motorista %>
        <p>
          <%= link_to "Show this motorista", motorista, class:"py-2 px-3 rounded-lg cursor-pointer transition duration-300 hover:bg-slate-800 hover:text-white" %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/motoristas/new.html.erb
<div class="p-5">
  <div class="mb-3">
    <span>
      <i class="fa-solid fa-chevron-left"></i>
      <%= link_to "Back to motoristas", motoristas_path %>
    </span>
    <h1 class="text-zinc-800 font-bold text-2xl">New motorista</h1>
  </div>

  <%= render "form", motorista: @motorista %>

  <br>
</div>

app/views/motoristas/search.html.erb
<div class="p-5">
  <div class="mb-3">
    <span>
      <i class="fa-solid fa-chevron-left"></i>
      <%= link_to "Back to motoristas", motoristas_path %>

    </span>
    <h1 class="text-zinc-800 font-bold text-2xl">Encontrar Rotas de um motorista</h1>
  </div>

  <% if !@error.to_s.empty? %>
    <p style="color: red" class="mb-3"><%= @error %></p>
  <% end %>
  <%= form_tag("/search/motorista", method: "post") do %>
    <%= label_tag(:cpf, "Cpf ou Nome:","style"=>"display:block;") %>
    <%= text_field_tag(:cpf) %>
    <%= submit_tag("Search", "class"=>"bg-blue-500 text-white rounded py-2 px-3 cursor-pointer transition duration-300 hover:bg-blue-600") %>
  <% end %>
</div>

app/views/motoristas/show.html.erb
<div class="p-5">
  <div class="mb-3">
    <span>
      <i class="fa-solid fa-chevron-left"></i>
      <%= link_to "Back to motoristas", motoristas_path %>
    </span>
    <h1 class="text-zinc-800 font-bold text-2xl">Visualizar Motorista</h1>
  </div>

  <div class="p-5 bg-white rounded-lg shadow-lg flex justify-between">
    <%= render @motorista %>

    <div class="flex flex-col gap-3">
      <%= link_to "Edit this motorista", edit_motorista_path(@motorista), class:"bg-slate-500 text-white rounded py-2 px-3 cursor-pointer transition duration-300 hover:bg-slate-600"  %>
      <%= button_to "Destroy this motorista", @motorista, method: :delete, class:"bg-red-500 text-white rounded py-2 px-3 cursor-pointer transition duration-300 hover:bg-red-600" %>
    </div>
  </div>
</div>

app/views/motoristas/show_result.html.erb
<div class="p-5">
  <div class="mb-3">
    <span>
      <i class="fa-solid fa-chevron-left"></i>
      <%= link_to "Back to find motorista", search_motorista_path %>
    </span>
    <h1 class="text-zinc-800 font-bold text-2xl">Rotas de <%= @motorista.nome %>, CPF: <%= @motorista.cpf %></h1>
  </div>

  <div id="rota" class="mt-3 flex flex-col gap-5">
    <% if @rotas.empty? %>
      <p>Nenhuma rota registrada</p>
    <%else%>
      <% @rotas.each do |rotum| %>
        <div class="p-5 bg-white rounded-lg shadow-lg flex justify-between">
          <%= render rotum %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>